/*
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

import (
	"net/http"
)

// APIClient manages communication with the Fingerprint Pro Server API API v3
// In most cases there should be only one, shared, APIClient.
type APIClient struct {
	cfg *Configuration

	// API Services

	FingerprintApi FingerprintApiServiceInterface
}

// NewAPIClient creates a new API client. Requires a userAgent string describing your application.
// optionally a custom http.Client to allow for advanced features such as caching.
func NewAPIClient(cfg *Configuration) *APIClient {
	if cfg == nil {
		cfg = NewConfiguration()
	}

	if cfg.HTTPClient == nil {
		cfg.HTTPClient = http.DefaultClient
	}

	c := &APIClient{}
	c.cfg = cfg

	// API Services
	c.FingerprintApi = &FingerprintApiService{cfg: cfg}

	return c
}
