/*
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

// This field is **deprecated** and will not return a result for **applications created after January 23rd, 2024**.  Please use the [IP Geolocation Smart signal](https://dev.fingerprint.com/docs/smart-signals-overview#ip-geolocation) for geolocation information.
type DeprecatedGeolocation struct {
	// The IP address is likely to be within this radius (in km) of the specified location.
	AccuracyRadius int32                     `json:"accuracyRadius,omitempty"`
	Latitude       float64                   `json:"latitude,omitempty"`
	Longitude      float64                   `json:"longitude,omitempty"`
	PostalCode     string                    `json:"postalCode,omitempty"`
	Timezone       string                    `json:"timezone,omitempty"`
	City           *GeolocationCity          `json:"city,omitempty"`
	Country        *GeolocationCountry       `json:"country,omitempty"`
	Continent      *GeolocationContinent     `json:"continent,omitempty"`
	Subdivisions   *[]GeolocationSubdivision `json:"subdivisions,omitempty"`
}
