/*
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

// Proximity ID represents a fixed geographical zone in a discrete global grid within which the device is observed.
type WebhookProximity struct {
	// A stable privacy-preserving identifier for a given proximity zone.
	Id string `json:"id"`
	// The radius of the proximity zone’s precision level, in meters.
	PrecisionRadius int32 `json:"precisionRadius"`
	// A value between `0` and `1` representing the likelihood that the true device location lies within the mapped proximity zone.   * Scores closer to `1` indicate high confidence that the location is inside the mapped proximity zone.   * Scores closer to `0` indicate lower confidence, suggesting the true location may fall in an adjacent zone.
	Confidence float32 `json:"confidence"`
}
