/*
 * Server API v3 (deprecated)
 *
 * > 🚧 Deprecation Notice > > This version of Server API is marked as deprecated starting on **Jan 7th 2026** and will be fully defunct on **Jan 7th 2027** according to our [API Deprecation Policy](https://dev.fingerprint.com/reference/api-deprecation-policy). If you still use this version, please follow our [migration guide](https://dev.fingerprint.com/reference/migrating-from-server-api-v3-to-v4) to migrate from this deprecated version to the new one.  Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

type Vpn struct {
	// VPN or other anonymizing service has been used when sending the request.
	Result     bool           `json:"result"`
	Confidence *VpnConfidence `json:"confidence"`
	// Local timezone which is used in timezoneMismatch method.
	OriginTimezone string `json:"originTimezone"`
	// Country of the request (only for Android SDK version >= 2.4.0, ISO 3166 format or unknown).
	OriginCountry string      `json:"originCountry"`
	Methods       *VpnMethods `json:"methods"`
}
