/*
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

type IpLocation struct {
	// The IP address is likely to be within this radius (in km) of the specified location.
	AccuracyRadius int32           `json:"accuracyRadius,omitempty"`
	Latitude       float64         `json:"latitude,omitempty"`
	Longitude      float64         `json:"longitude,omitempty"`
	PostalCode     string          `json:"postalCode,omitempty"`
	Timezone       string          `json:"timezone,omitempty"`
	City           *IpLocationCity `json:"city,omitempty"`
	Country        *Location       `json:"country,omitempty"`
	Continent      *Location       `json:"continent,omitempty"`
	Subdivisions   []Subdivision   `json:"subdivisions,omitempty"`
}
