/*
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

// Contains all information about the request identified by `requestId`, depending on the pricing plan (Pro, Pro Plus, Enterprise)
type Products struct {
	Identification      *ProductIdentification      `json:"identification,omitempty"`
	Botd                *ProductBotd                `json:"botd,omitempty"`
	RootApps            *ProductRootApps            `json:"rootApps,omitempty"`
	Emulator            *ProductEmulator            `json:"emulator,omitempty"`
	IpInfo              *ProductIpInfo              `json:"ipInfo,omitempty"`
	IpBlocklist         *ProductIpBlocklist         `json:"ipBlocklist,omitempty"`
	Tor                 *ProductTor                 `json:"tor,omitempty"`
	Vpn                 *ProductVpn                 `json:"vpn,omitempty"`
	Proxy               *ProductProxy               `json:"proxy,omitempty"`
	Incognito           *ProductIncognito           `json:"incognito,omitempty"`
	Tampering           *ProductTampering           `json:"tampering,omitempty"`
	ClonedApp           *ProductClonedApp           `json:"clonedApp,omitempty"`
	FactoryReset        *ProductFactoryReset        `json:"factoryReset,omitempty"`
	Jailbroken          *ProductJailbroken          `json:"jailbroken,omitempty"`
	Frida               *ProductFrida               `json:"frida,omitempty"`
	PrivacySettings     *ProductPrivacySettings     `json:"privacySettings,omitempty"`
	VirtualMachine      *ProductVirtualMachine      `json:"virtualMachine,omitempty"`
	RawDeviceAttributes *ProductRawDeviceAttributes `json:"rawDeviceAttributes,omitempty"`
	HighActivity        *ProductHighActivity        `json:"highActivity,omitempty"`
	LocationSpoofing    *ProductLocationSpoofing    `json:"locationSpoofing,omitempty"`
	SuspectScore        *ProductSuspectScore        `json:"suspectScore,omitempty"`
	RemoteControl       *ProductRemoteControl       `json:"remoteControl,omitempty"`
	Velocity            *ProductVelocity            `json:"velocity,omitempty"`
	DeveloperTools      *ProductDeveloperTools      `json:"developerTools,omitempty"`
}
