/*
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

// ErrorCode : Error code:  * `RequestCannotBeParsed` - the query parameters or JSON payload contains some errors            that prevented us from parsing it (wrong type/surpassed limits).  * `TokenRequired` - `Auth-API-Key` header is missing or empty.  * `TokenNotFound` - no Fingerprint application found for specified secret key.  * `SubscriptionNotActive` - Fingerprint application is not active.  * `WrongRegion` - server and application region differ.  * `FeatureNotEnabled` - this feature (for example, Delete API) is not enabled for your application.  * `RequestNotFound` - the specified request ID was not found. It never existed, expired, or it has been deleted.  * `VisitorNotFound` - The specified visitor ID was not found. It never existed or it may have already been deleted.  * `TooManyRequests` - the limit on secret API key requests per second has been exceeded.  * `429 Too Many Requests` - the limit on secret API key requests per second has been exceeded.  * `StateNotReady` - The event specified with request id is           not ready for updates yet. Try again.           This error happens in rare cases when update API is called immediately           after receiving the request id on the client. In case you need to send           information right away, we recommend using the JS agent API instead.  * `Failed` - internal server error.
type ErrorCode string

// List of ErrorCode
const (
	REQUEST_CANNOT_BE_PARSED ErrorCode = "RequestCannotBeParsed"
	TOKEN_REQUIRED           ErrorCode = "TokenRequired"
	TOKEN_NOT_FOUND          ErrorCode = "TokenNotFound"
	SUBSCRIPTION_NOT_ACTIVE  ErrorCode = "SubscriptionNotActive"
	WRONG_REGION             ErrorCode = "WrongRegion"
	FEATURE_NOT_ENABLED      ErrorCode = "FeatureNotEnabled"
	REQUEST_NOT_FOUND        ErrorCode = "RequestNotFound"
	VISITOR_NOT_FOUND        ErrorCode = "VisitorNotFound"
	TOO_MANY_REQUESTS        ErrorCode = "TooManyRequests"
	TOOMANYREQUESTS429       ErrorCode = "429 Too Many Requests"
	STATE_NOT_READY          ErrorCode = "StateNotReady"
	FAILED                   ErrorCode = "Failed"
)
