/*
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

// ErrorCode : Error code:  * `RequestCannotBeParsed` - the query parameters or JSON payload contains some errors            that prevented us from parsing it (wrong type/surpassed limits).  * `TokenRequired` - `Auth-API-Key` header is missing or empty.  * `TokenNotFound` - no Fingerprint application found for specified secret key.  * `SubscriptionNotActive` - Fingerprint application is not active.  * `WrongRegion` - server and application region differ.  * `FeatureNotEnabled` - this feature (for example, Delete API) is not enabled for your application.  * `RequestNotFound` - the specified request ID was not found. It never existed, expired, or it has been deleted.  * `VisitorNotFound` - The specified visitor ID was not found. It never existed or it may have already been deleted.  * `TooManyRequests` - the limit on secret API key requests per second has been exceeded.  * `429 Too Many Requests` - the limit on secret API key requests per second has been exceeded.  * `StateNotReady` - The event specified with request id is           not ready for updates yet. Try again.           This error happens in rare cases when update API is called immediately           after receiving the request id on the client. In case you need to send           information right away, we recommend using the JS agent API instead.  * `Failed` - internal server error.
type ErrorCode string

// List of ErrorCode
const (
	ErrorCode_REQUEST_CANNOT_BE_PARSED ErrorCode = "RequestCannotBeParsed"
	ErrorCode_TOKEN_REQUIRED           ErrorCode = "TokenRequired"
	ErrorCode_TOKEN_NOT_FOUND          ErrorCode = "TokenNotFound"
	ErrorCode_SUBSCRIPTION_NOT_ACTIVE  ErrorCode = "SubscriptionNotActive"
	ErrorCode_WRONG_REGION             ErrorCode = "WrongRegion"
	ErrorCode_FEATURE_NOT_ENABLED      ErrorCode = "FeatureNotEnabled"
	ErrorCode_REQUEST_NOT_FOUND        ErrorCode = "RequestNotFound"
	ErrorCode_VISITOR_NOT_FOUND        ErrorCode = "VisitorNotFound"
	ErrorCode_TOO_MANY_REQUESTS        ErrorCode = "TooManyRequests"
	ErrorCode_TOOMANYREQUESTS429       ErrorCode = "429 Too Many Requests"
	ErrorCode_STATE_NOT_READY          ErrorCode = "StateNotReady"
	ErrorCode_FAILED                   ErrorCode = "Failed"
)
