/*
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. This API can be used for data exports, decision-making, and data analysis scenarios.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

import (
	"time"
)

type WebhookVisit struct {
	VisitorId      string                `json:"visitorId"`
	ClientReferrer string                `json:"clientReferrer,omitempty"`
	UserAgent      string                `json:"userAgent,omitempty"`
	Bot            *BotdDetectionResult  `json:"bot,omitempty"`
	IpInfo         *SignalResponseIpInfo `json:"ipInfo,omitempty"`
	// Flag if user used incognito session.
	Incognito   bool                       `json:"incognito"`
	RootApps    *SignalResponseRootApps    `json:"rootApps,omitempty"`
	Emulator    *SignalResponseEmulator    `json:"emulator,omitempty"`
	IpBlocklist *SignalResponseIpBlocklist `json:"ipBlocklist,omitempty"`
	Tor         *SignalResponseTor         `json:"tor,omitempty"`
	Vpn         *SignalResponseVpn         `json:"vpn,omitempty"`
	Proxy       *SignalResponseProxy       `json:"proxy,omitempty"`
	Tampering   *SignalResponseTampering   `json:"tampering,omitempty"`
	// Unique identifier of the user's identification request.
	RequestId      string          `json:"requestId"`
	BrowserDetails *BrowserDetails `json:"browserDetails"`
	Ip             string          `json:"ip"`
	IpLocation     *IpLocation     `json:"ipLocation"`
	// Timestamp of the event with millisecond precision in Unix time.
	Timestamp int64 `json:"timestamp"`
	// Time expressed according to ISO 8601 in UTC format.
	Time *time.Time `json:"time"`
	// Page URL from which identification request was sent.
	Url string `json:"url"`
	// A customer-provided value or an object that was sent with identification request.
	Tag ModelMap `json:"tag,omitempty"`
	// A customer-provided id that was sent with identification request.
	LinkedId   string      `json:"linkedId,omitempty"`
	Confidence *Confidence `json:"confidence"`
	// Attribute represents if a visitor had been identified before.
	VisitorFound bool    `json:"visitorFound"`
	FirstSeenAt  *SeenAt `json:"firstSeenAt"`
	LastSeenAt   *SeenAt `json:"lastSeenAt"`
}
