/*
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API provides a way for validating visitors’ data issued by Fingerprint Pro.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

type IpLocation struct {
	AccuracyRadius int32           `json:"accuracyRadius"`
	Latitude       float64         `json:"latitude"`
	Longitude      float64         `json:"longitude"`
	PostalCode     string          `json:"postalCode,omitempty"`
	Timezone       string          `json:"timezone"`
	City           *IpLocationCity `json:"city,omitempty"`
	Country        *Location       `json:"country"`
	Continent      *Location       `json:"continent"`
	Subdivisions   []Subdivision   `json:"subdivisions,omitempty"`
}
