/*
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

import (
	"time"
)

// Proxy detection details (present if proxy is detected)
type ProxyDetails struct {
	// Residential proxies use real user IP addresses to appear as legitimate traffic,  while data center proxies are public proxies hosted in data centers
	ProxyType string `json:"proxyType"`
	// ISO 8601 formatted timestamp in UTC with hourly resolution of when this IP was last seen as a proxy when available.
	LastSeenAt *time.Time `json:"lastSeenAt,omitempty"`
}
