/*
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

import (
	"time"
)

// Contains all the information from Bot Detection product
type Botd struct {
	Bot  *BotdBot  `json:"bot"`
	Meta *ModelMap `json:"meta,omitempty"`
	// A customer-provided id that was sent with the request.
	LinkedId string `json:"linkedId,omitempty"`
	// Page URL from which the request was sent.
	Url string `json:"url"`
	// IP address of the requesting browser or bot.
	Ip string `json:"ip"`
	// Time in UTC when the request from the JS agent was made. We recommend to treat requests that are older than 2 minutes as malicious. Otherwise, request replay attacks are possible.
	Time      *time.Time `json:"time"`
	UserAgent string     `json:"userAgent"`
	// Unique identifier of the user's request.
	RequestId string `json:"requestId"`
}
