/*
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API provides a way for validating visitors’ data issued by Fingerprint Pro.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

type BrowserDetails struct {
	BrowserName         string `json:"browserName"`
	BrowserMajorVersion string `json:"browserMajorVersion"`
	BrowserFullVersion  string `json:"browserFullVersion"`
	Os                  string `json:"os"`
	OsVersion           string `json:"osVersion"`
	Device              string `json:"device"`
	UserAgent           string `json:"userAgent"`
	BotProbability      int32  `json:"botProbability,omitempty"`
}
