/*
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

type VpnMethods struct {
	// The browser timezone doesn't match the timezone inferred from the request IP address.
	TimezoneMismatch bool `json:"timezoneMismatch"`
	// Request IP address is owned and used by a public VPN service provider.
	PublicVPN bool `json:"publicVPN"`
	// This method applies to mobile devices only. Indicates the result of additional methods used to detect a VPN in mobile devices.
	AuxiliaryMobile bool `json:"auxiliaryMobile"`
	// The browser runs on a different operating system than the operating system inferred from the request network signature.
	OsMismatch bool `json:"osMismatch"`
	// Request IP address belongs to a relay service provider, indicating the use of relay services like [Apple Private relay](https://support.apple.com/en-us/102602) or [Cloudflare Warp](https://developers.cloudflare.com/warp-client/).   * Like VPNs, relay services anonymize the visitor's true IP address. * Unlike traditional VPNs, relay services don't let visitors spoof their location by choosing an exit node in a different country.  This field allows you to differentiate VPN users and relay service users in your fraud prevention logic.
	Relay bool `json:"relay"`
}
