/*
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

// Fields `lastTimestamp` and `paginationKey` added when `limit` or `before` parameter provided and there is more data to show
type Response struct {
	VisitorId string           `json:"visitorId"`
	Visits    []ResponseVisits `json:"visits"`
	// ⚠️ Deprecated paging attribute, please use `paginationKey` instead. Timestamp of the last visit in the current page of results.
	LastTimestamp int64 `json:"lastTimestamp,omitempty"`
	// Request ID of the last visit in the current page of results. Use this value in the following request as the `paginationKey` parameter to get the next page of results.
	PaginationKey string `json:"paginationKey,omitempty"`
}
