/*
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

type Vpn struct {
	// VPN or other anonymizing service has been used when sending the request.
	Result     bool           `json:"result"`
	Confidence *VpnConfidence `json:"confidence"`
	// Local timezone which is used in timezoneMismatch method.
	OriginTimezone string `json:"originTimezone"`
	// Country of the request (only for Android SDK version >= 2.4.0, ISO 3166 format or unknown).
	OriginCountry string      `json:"originCountry"`
	Methods       *VpnMethods `json:"methods"`
}
