/*
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

// Contains a list of all identification events matching the specified search criteria.
type SearchEventsResponse struct {
	Events []SearchEventsResponseEvents `json:"events,omitempty"`
	// Use this value in the `pagination_key` parameter to request the next page of search results.
	PaginationKey string `json:"paginationKey,omitempty"`
}
