/*
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

// ProxyConfidence : Confidence level of the proxy detection. If a proxy is not detected, confidence is \"high\". If it's detected, can be \"low\", \"medium\", or \"high\".
type ProxyConfidence string

// List of ProxyConfidence
const (
	ProxyConfidence_LOW    ProxyConfidence = "low"
	ProxyConfidence_MEDIUM ProxyConfidence = "medium"
	ProxyConfidence_HIGH   ProxyConfidence = "high"
)
