/*
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. This API can be used for data exports, decision-making, and data analysis scenarios.
 *
 * API version: 3
 * Contact: support@fingerprint.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk

type SignalResponseRootApps struct {
	Data   *SignalResponseRootAppsData `json:"data,omitempty"`
	Error_ *ProductError               `json:"error,omitempty"`
}
